### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Saulzar** [osa1/hslua#15]
Hi, 

So I've been using hslua for making a wrapper for cloud haskell distributed lua.
(to use from the torch machine learning toolkit).

In the process I've changed hslua to use the exception handling everywhere and removed the Maybe type in peek for the StackValue class, as well as the valuetype function.

So now the type is not checked at the LuaImport call site (instead it just catches exceptions and throws an ArgError with the same message).

The StackValue instance will do some kind of type assertion and throw an exception, so now I can check the type of record fields for example, and have it say something like.

dist-lua: [string "config.lua"]:23: bad argument #1 to 'updateFiles' (non numeric index in array)

or 

dist-lua: [string "config.lua"]:66: bad argument #3 to 'spawnNode' (converting field 'port', expected: number got: string)

I've also created quite a lot of code for marshalling Haskell types and torch types (including records), using StackValue - I've also updated the LuaUtils package. I use serialization to opaquely store complicated Haskell values in Lua and Lua values in Haskell.

I'm thinking of combining the two, and have what is currently LuaUtils as Scripting.Lua.Containers, and maybe add a Scripting.Lua.Torch.

Let me know what you think.

**Comment by tarleb** [comment]
I incorporated many of the ideas into hslua, feedback is very welcome.  Error handling / messages are still a problem though, as errors in some functions (e.g. `settable`) still cannot be caught and cause the host program to terminate; see #43.
