### ISSUE TITLE
Should use ByteString instead of String

### ISSUE THREAD

**Issue by feuerbach** [osa1/hslua#23]
Thanks for the library!

Is there any reason why this uses String to represent lua strings (which are bytestrings)?

**Comment by osa1** [comment]
We had a long discussion about this here https://github.com/osa1/hslua/pull/17 , in the end I was convinced that this needs to be done but I just couldn't spare time for this and then I forgot! Sorry!

I'll try to get this done this weekend.

(or, as usual, pull requests are welcome :-) )

**Comment by osa1** [comment]
This is now implemented. I'll add some tests and then push a new major release to Hackage.

**Comment by osa1** [comment]
New release pushed to Hackage as 0.4.0.
