### ISSUE TITLE
Compile failure on ghc 7.6.3 - can't find `B.unsafePackMallocCStringLen`

### ISSUE THREAD

**Issue by jgm** [osa1/hslua#28]
See https://travis-ci.org/jgm/pandoc/jobs/64786014 for full log.
```
Preprocessing library hslua-0.4.0...
[1 of 2] Compiling Scripting.Lua.Raw ( dist/build/Scripting/Lua/Raw.hs, dist/build/Scripting/Lua/Raw.o )
[2 of 2] Compiling Scripting.Lua    ( dist/build/Scripting/Lua.hs, dist/build/Scripting/Lua.o )
src/Scripting/Lua.hsc:200:5:
    Not in scope: `B.unsafePackMallocCStringLen'
    Perhaps you meant one of these:
      `B.unsafePackMallocCString' (imported from Data.ByteString.Unsafe),
      `B.unsafePackCStringLen' (imported from Data.ByteString.Unsafe)
```
Sorry, the log doesn't show the bytestring version.  But I see from the [git log](https://github.com/haskell/bytestring/commit/aa31ed160d95aec2bbfea5b4c020a4f0fd33c222) that this function was added to bytestring on June 20, 2012.  So you probably need a `bytestring >= 0.10` constraint.  Or, better, use some CPP so that hslua will still build against older versions of bytestring, which are still common.  One way or the other, could you push a fixed package? Otherwise builds that depend on hslua will fail.

**Comment by osa1** [comment]
We already had a `bytestring >= 0.10` constraint, but apparently that's not enough because this function is added with `0.10.2.0`.

I updated Hackage version(without pushing a new version, just run a `cabal update`) and pushed fixed Cabal file to the repo.

Thanks for reporting.

**Comment by jgm** [comment]
Great, thanks!

+++ Ömer Sinan Ağacan [Jun 01 15 07:13 ]:
