### ISSUE TITLE
Needs more tests

### ISSUE THREAD

**Issue by ajnsit** [osa1/hslua#31]
Hi,

Just wondering if there are plans to add more tests for HsLua? The StackValue instances in particular lend themselves well to randomised QuickCheck testing.

If there are no specific plans then I can write some to test the stack value instances.

**Comment by osa1** [comment]
More tests and contributions are always welcome! Currently we only have a couple of unit tests for very basic stuff and some test programs for more advanced things(like `err_prop` program that tests error propagation from Haskell to Lua and from Lua to Haskell).

**Comment by osa1** [comment]
FWIW, I just enabled coverage checking and it turns out we already have 67% test coverage ;-)

**Comment by ajnsit** [comment]
I added some tests in https://github.com/osa1/hslua/pull/33

**Comment by osa1** [comment]
#33 is merged. Feel free to close this if you're satisfied with the test coverage.

**Comment by ajnsit** [comment]
Thanks! I'll close this issue for now, as I don't have any specific tests in mind.
