### ISSUE TITLE
callfunc with string 

### ISSUE THREAD

**Issue by ka3a4ok** [osa1/hslua#32]
This code doesn't compile

```haskell
Lua.callfunc l "print" (Data.ByteString.Char8.pack "Hello")
```
Error:
```
    No instance for (Lua.StackValue a0)
      arising from a use of `Lua.callfunc'
    The type variable `a0' is ambiguous
    Note: there are several potential instances:
      instance Lua.StackValue Lua.LuaInteger
        -- Defined in `Scripting.Lua'
      instance Lua.StackValue (GHC.Ptr.FunPtr Lua.LuaCFunction)
        -- Defined in `Scripting.Lua'
      instance Lua.StackValue (GHC.Ptr.Ptr a)
        -- Defined in `Scripting.Lua'
      ...plus 7 others
```

How can I use callfunc with ByteStrings?

**Comment by osa1** [comment]
It's not a ByteString issue -- GHC can't figure out the expected return value of the called function(`print`). It should be inferred from the call site, you may either annotate your expression with types or somehow refactor your code to allow GHC to infer that.

As an example, this won't work:

```haskell
module Main where

import Scripting.Lua

main = do
  l <- newstate
  openlibs l
  -- this fails, because GHC can't infer return type:
  callfunc l "print" (10 :: Int)
  close l
```

If I annotate the type or let GHC infer that somehow, it works:


```haskell
main = do
  l <- newstate
  openlibs l
  () <- callfunc l "print" (10 :: Int)
  close l
```

or similarly, `callfunc l "print" (10 :: Int) :: IO ()` also works. In your case, you can do `callfunc l "print" (BC.pack "blah") :: IO ()`.
