### ISSUE TITLE
Random Error with hsmethod__call

### ISSUE THREAD

**Issue by coleingraham** [osa1/hslua#35]
Hi there,
I'm currently using hslua in a project where I'm scripting opengl drawing with lua. I've been running into a crash at random times caused by a pattern match failure in hsmethod__call. Since I have calls back and forth between lua and haskell hundreds of times per second I'm assuming something is getting lost somewhere that I can't isolate. To get around this I patched the function to return 0 if it gets Nothing (which is the only thing I can think of what would be causing this):

``` haskell
hsmethod__call l = do
    ptr <- peek l 1
    case ptr of
        Nothing -> return 0
        Just ptr -> do
        remove l 1
        stableptr <- F.peek (castPtr ptr)
        f <- deRefStablePtr stableptr
        f l
```

Is there anything anyone could suggest that would make this patch unnecessary?

**Comment by osa1** [comment]
Are you calling `hsmethod__call` from your C code? Normally that code is supposed to be called by Lua when you try to call a `userdata` pushed by `pushhsfunction` or `pushrawhsfunction`(`registerhsfunction` and `regusterrawhsfunction` also work, of course). The code is assuming that the userdata is pushed to the stack already, so if you're having a pattern match failure, that means somehow the userdata(actually a Haskell function) is not pushed to the stack. I can try to help if you give more context, maybe show the calling code etc.

The problem with your patch is that it's hiding a very important error, namely, if you forgot to push a function before calling `hsmethod__call` or push a function that doesn't return anything, `hsmethod__call` returns same thing, you can't tell the difference.

Currently error handling is not great, but at least it's failing in some way.

**Comment by tarleb** [comment]
Error handling changed slightly in that `peek` now throws an haskell exception whenever the conversion fails. This should help in this case.  Feel free to reopen if you think the current solution isn't satisfactory.
