### ISSUE TITLE
lualib_in_haskell example not working properly with LuaJIT

### ISSUE THREAD

**Issue by osa1** [osa1/hslua#37]
For some reason when run with LuaJIT, `gettop` in `add` function is returning `-1`, which is very weird because it should be at least `0`(which means no arguments are passed). Expected value is `2`.

**Comment by tarleb** [comment]
I can no longer reproduce this specific problem, but got a similar behavior when running a library compiled against lua 5.3.4 with lua 5.1.5: gettop consistently returned `-1311` in that case. I'm hence going to assume that the described issue was due to a mismatch in lua versions.
