### ISSUE TITLE
Integrate LibArith into test suite

### ISSUE THREAD

**Issue by osa1** [osa1/hslua#38]
Now that we pushed it to the repo, we should make sure it's running with latest hslua.

**Comment by tarleb** [comment]
I've moved all examples to [hslua-examples](https://github.com/hslua/hslua-examples) and test with travis.  This allows us to keep the main repo small and lightweight; the downside is that extra care has to be taken to ensure that the examples stay up-to-date. A travis cron job might be a good way to achieve this.
