### ISSUE TITLE
Embed LuaJIT as an alternative to Lua 5.1

### ISSUE THREAD

**Issue by raphaelcohn** [osa1/hslua#39]
In the current source tree, there's Lua 5.1, and it's possible to build hslua to use a system LuaJIT. It'd be really nice to embed LuaJIT into the hslua source tree, so it becomes something that Pandoc could switch to (see https://github.com/jgm/pandoc/issues/2452). If Pandoc used LuaJIT, all sorts of interesting custom writers are possible that 'bind on the fly' to C lib APIs...

**Comment by osa1** [comment]
Sure, as long as there is no problems with licensing, I don't see any reasons why not ship with LuaJIT instead of PUC-Lua.

(will look into this later)

**Comment by tarleb** [comment]
I'm closing this, as it conflicts with our switch to using lua 5.3 per default.  It's still possible to use LuaJIT by passing the `-fluajit` flag to cabal (see also the README), which might be even more important now that the upcoming pandoc release have lua filters built-in.  However, I don't believe that LuaJIT sources should be included here.
