### ISSUE TITLE
Standard Lua Libraries

### ISSUE THREAD

**Issue by Hypoon** [osa1/hslua#41]
Currently, hslua exposes LuaL_openlibs to facilitate loading the standard libraries. This provides all-or-none functionality, leaving no clear way to load standard libraries one-by-one (without resorting to FFI, which defeats the purpose of hslua, right?).

The appropriate way of loading standard libraries individually appears to vary between 5.1 and later versions. In 5.1, [the manual](http://www.lua.org/manual/5.1/manual.html#5) suggests using lua_call, presumably by first using lua_pushcfunction.

Should hslua provide functions to load each of the standard libraries individually? Or should it simply expose the C functions, such hslua users can feed them into lua_pushcfunction?

Thanks!

**Comment by osa1** [comment]
@Hypoon I just implemented those functions. Have a look at new tests to see how to use. I added functions like `opentable :: LuaState -> IO ()` that takes care of `lua_pushcfunction` and `lua_call`, so you just call `opentable`, `openio` etc.

**Comment by osa1** [comment]
I bumped the version number and updated the changelog. Tell me if this works for you and I'll upload a new version to Hackage.
