### ISSUE TITLE
add hslua to stackage?

### ISSUE THREAD

**Issue by juhp** [osa1/hslua#44]
I was trying to `stack build` pandoc with current Stackage Nightly but couldn't because hslua is not officially listed as a Stackage package (it was pulled in by pandoc earlier but pandoc was disabled when Nightly moved to ghc8).

Anyway how about adding hslua to Stackage?

(If you don't want to I can also add it under my name.)

**Comment by juhp** [comment]
Okay sorry I went ahead and I added it under my name, but PR is all that is needed to move it over to you, which I would prefer anyway.

**Comment by osa1** [comment]
I'm not maintaining hslua anymore and I'm looking for a new maintainer (sent a mail to Haskell-cafe a couple of months ago). It's fine if you add it under your name as I won't be maintaining anyway.

I'll update the README today to mention that the package is currently not maintained and is looking for a maintainer.

**Comment by tarleb** [comment]
Fixed via fpco/stackage#2405.
