### ISSUE TITLE
Where are the XXX instances?

### ISSUE THREAD

**Issue by xaviershay** [osa1/hslua#55]
Hello, and thank you for this library!

https://wiki.haskell.org/HsLua mentions `XXX` instances for dealing with heterogenous lists, but I can't find them in the documentation anywhere. Do they still exist? Were they removed? (This documentation is out of date in other ways - `dostring` doesn't appear to exist anymore either)

A problem I have is that I'm trying to map various data-structures to haskell, and if I get the types wrong I get `Nothing` ... but no way to introspect what the "raw value" is so I just have to keep guessing until I figure it out. I guess I'm looking for a way to get more debug visibility into the `LuaState`.

**Comment by xaviershay** [comment]
relevant: I was able to use [hslua-aeson](https://github.com/tarleb/hslua-aeson/blob/master/src/Scripting/Lua/Aeson.hs) to "inspect" arbitrary values quite nicely.

**Comment by tarleb** [comment]
Hi Xavier,

Thanks for the report. I agree, a more generic data structure is currently missing and should be added. I'm working on pandoc's lua subsystem and plan to use the gained insights to improve hslua. A generic `StackValue` instance will be part of that effort.

The `XXX` instance is a curiosity to me.  It seems to be completely undocumented and I couldn't find any reference to it even in older hslua versions. Glad to hear that hslua-aeson is working for you.  I found it to be ~50% slower than hand-tuned instances, which is probably still acceptable for most use-cases.

Documentation is a problem.  Personally, I read the official C API docs first and then followed it up with the haddock module page, example programs, and pandoc sources after that. I sure hope to improve that situation as well some day, but I'm not a native speaker, which makes it even harder.

**Comment by tarleb** [comment]
I re-added `dostring` and opened a new issue to keep track of the "inspection" issue (see #57).
