### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by snoyberg** [osa1/hslua#58]
```
Failures:

  test/HsLuaSpec.hs:201: 
  1) HsLua, luaopen_* functions, opentable
       load failed
       expected: 0
        but got: 6

  test/HsLuaSpec.hs:201: 
  2) HsLua, luaopen_* functions, openio
       load failed
       expected: 0
        but got: 6

  test/HsLuaSpec.hs:201: 
  3) HsLua, luaopen_* functions, openos
       load failed
       expected: 0
        but got: 6

  test/HsLuaSpec.hs:201: 
  4) HsLua, luaopen_* functions, openstring
       load failed
       expected: 0
        but got: 6

  test/HsLuaSpec.hs:201: 
  5) HsLua, luaopen_* functions, openmath
       load failed
       expected: 0
        but got: 6
```

**Comment by tarleb** [comment]
Thanks for the report. Which version of hslua are you using? The file `test/HsLuaSpec` is no longer present in versions >= 0.6.  One possible cause might be an old/uncleaned dist folder, could that be it?

**Comment by snoyberg** [comment]
We were constrained to hslua 0.5 due to the upper bound present in hslua-aeson. I'm going to drop hslua-aeson from Stackage for now to allow the newer version to come in.

**Comment by tarleb** [comment]
:+1: thanks. I'm currently updating hslua-aeson to work with hslua-0.6.

**Comment by tarleb** [comment]
I've updated hslua-aeson to work with the current hslua version (0.8.0), so I guess this can be closed now. Please reopen if more changes are necessary.
